Try build + run WebHost.Endpoint tests and ServiceModel tests.

diff --git a/.github/workflows/build-servicestack.yml b/.github/workflows/build-servicestack.yml
--- a/.github/workflows/build-servicestack.yml
+++ b/.github/workflows/build-servicestack.yml
@@ -35,18 +35,6 @@ jobs:
           path: ./ServiceStack/tests/ServiceStack.Common.Tests/TestResults/results.trx
           reporter: dotnet-trx
 
-      - name: Test ServiceHosts
-        run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.ServiceHost.Tests/ServiceStack.ServiceHost.Tests.csproj --logger 'trx;LogFileName=results.trx'
-
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: ServiceHost Tests
-          only-summary: 'true'
-          path: ./ServiceStack/tests/ServiceStack.ServiceHost.Tests/TestResults/results.trx
-          reporter: dotnet-trx
-
       - name: Test ServiceModels
         run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.ServiceModel.Tests/ServiceStack.ServiceModel.Tests.csproj --logger 'trx;LogFileName=results.trx'
 
@@ -71,15 +59,15 @@ jobs:
           path: ./ServiceStack/tests/ServiceStack.WebHost.Endpoints.Tests/TestResults/results.trx
           reporter: dotnet-trx
 
-      - name: Test OpenApi
-        run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.OpenApi.Tests/ServiceStack.OpenApi.Tests.csproj --logger 'trx;LogFileName=results.trx'
-
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: OpenApi Tests
-          path: ./ServiceStack/tests/ServiceStack.OpenApi.Tests/TestResults/results.trx
-          reporter: dotnet-trx
+#      - name: Test OpenApi
+#        run: dotnet test --framework net6.0 ./ServiceStack/tests/ServiceStack.OpenApi.Tests/ServiceStack.OpenApi.Tests.csproj --logger 'trx;LogFileName=results.trx'
+#
+#      - name: Test Report
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: OpenApi Tests
+#          path: ./ServiceStack/tests/ServiceStack.OpenApi.Tests/TestResults/results.trx
+#          reporter: dotnet-trx
         
     
