Run redis tests and reports.

diff --git a/.github/workflows/build-redis.yml b/.github/workflows/build-redis.yml
--- a/.github/workflows/build-redis.yml
+++ b/.github/workflows/build-redis.yml
@@ -5,6 +5,7 @@ on:
     paths:
       - 'ServiceStack.Redis/**'
       - 'ServiceStack.Text/**'
+      - '.github/**'
 
 jobs:
   build-redis:
@@ -31,11 +32,30 @@ jobs:
         working-directory: ServiceStack.Redis/build
         run: dotnet build ./build.proj
         
+      - name: Env setup
+        run: |
+          echo "SERVICESTACK_LICENSE=${{ secrets.SERVICESTACK_LICENSE }}" >> $GITHUB_ENV
+        
       - name: Test Without Integration
         working-directory: ServiceStack.Redis/tests
-        run: dotnet test --framework net6.0 ./ServiceStack.Redis.Tests/ServiceStack.Redis.Tests.csproj --filter TestCategory\!=Integration
+        run: dotnet test --framework net6.0 ./ServiceStack.Redis.Tests/ServiceStack.Redis.Tests.csproj --filter TestCategory\!=Integration --logger 'trx;LogFileName=non-integration-results.trx'
       
       - name: Test With Integration
         working-directory: ServiceStack.Redis/tests
-        run: dotnet test --framework net6.0 ./ServiceStack.Redis.Tests/ServiceStack.Redis.Tests.csproj --filter TestCategory=Integration
-    
+        run: dotnet test --framework net6.0 ./ServiceStack.Redis.Tests/ServiceStack.Redis.Tests.csproj --filter TestCategory=Integration --logger 'trx;LogFileName=integration-results.trx'
+
+      - name: Non-Integration Tests Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: OrmLite Tests                                                         # Name of the check run which will be created
+          path: ./ServiceStack.Redis/tests/ServiceStack.Redis.Tests/TestResults/non-integration-results.trx       # Path to test results
+          reporter: dotnet-trx                                                        # Format of test results
+          
+      - name: Integration Tests Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure() # run this step even if previous step failed
+        with:
+          name: OrmLite Tests                                                         # Name of the check run which will be created
+          path: ./ServiceStack.Redis/tests/ServiceStack.Redis.Tests/TestResults/integration-results.trx       # Path to test results
+          reporter: dotnet-trx                                                        # Format of test results
