Clean up workflows.

diff --git a/.github/workflows/build-azure.yml b/.github/workflows/build-azure.yml
--- a/.github/workflows/build-azure.yml
+++ b/.github/workflows/build-azure.yml
@@ -31,15 +31,16 @@ jobs:
         run: |
           echo "SERVICESTACK_LICENSE=${{ secrets.SERVICESTACK_LICENSE }}" >> $GITHUB_ENV
 
-      - name: Azure Tests
-        run: dotnet test --framework net6.0 ./ServiceStack.Azure/tests/ServiceStack.Azure.Tests/ServiceStack.Azure.Tests.csproj  --logger 'trx;LogFileName=results.trx'
-
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: (success() || failure()) && steps.test_integration.outcome != 'skipped'
-        with:
-          name: Text Tests
-          path: ./ServiceStack.Azure/tests/ServiceStack.Azure.Tests/TestResults/results.trx
-          reporter: dotnet-trx
-          only-summary: 'true'
+# Azure tests need mocking.
+#      - name: Azure Tests
+#        run: dotnet test --framework net6.0 ./ServiceStack.Azure/tests/ServiceStack.Azure.Tests/ServiceStack.Azure.Tests.csproj  --logger 'trx;LogFileName=results.trx'
+#
+#      - name: Test Report
+#        uses: dorny/test-reporter@v1
+#        if: (success() || failure()) && steps.test_integration.outcome != 'skipped'
+#        with:
+#          name: Text Tests
+#          path: ./ServiceStack.Azure/tests/ServiceStack.Azure.Tests/TestResults/results.trx
+#          reporter: dotnet-trx
+#          only-summary: 'true'
           
