Try generate test report.

diff --git a/.github/workflows/build-ormlite.yml b/.github/workflows/build-ormlite.yml
--- a/.github/workflows/build-ormlite.yml
+++ b/.github/workflows/build-ormlite.yml
@@ -64,4 +64,12 @@ jobs:
         working-directory: ServiceStack.OrmLite/tests
         env:
           ORMLITE_DIALECT: Sqlite
-        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.SqliteTests/ServiceStack.OrmLite.SqliteTests.csproj
+        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.SqliteTests/ServiceStack.OrmLite.SqliteTests.csproj --logger 'trx;LogFileName=test-results.trx'
+
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: OrmLite Tests         # Name of the check run which will be created
+          path: test-results.trx      # Path to test results
+          reporter: dotnet-trx        # Format of test results
