Try OrmLite tests with multiple providers.

diff --git a/.github/workflows/integration-ormlite.yml b/.github/workflows/integration-ormlite.yml
--- a/.github/workflows/integration-ormlite.yml
+++ b/.github/workflows/integration-ormlite.yml
@@ -28,6 +28,22 @@ jobs:
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
+        sqlserver:
+          image: mcr.microsoft.com/mssql/server:2019-latest
+          env:
+            ACCEPT_EULA: Y
+            SA_PASSWORD: Test!tesT
+            MSSQL_PID: Developer
+          ports:
+            - 48501:1433
+        mysql:
+          image: mysql:8.0.28
+          env:
+            MYSQL_ROOT_PASSWORD: test
+            MYSQL_DATABASE: test
+            MYSQL_USER: root
+          ports:
+            - 48201:3306
     steps:
       - uses: actions/checkout@v2
       - name: Setup dotnet
@@ -48,18 +64,32 @@ jobs:
         working-directory: ServiceStack.OrmLite/tests
         run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.Tests.Setup/ServiceStack.OrmLite.Tests.Setup.csproj        
 
-      - name: Test PostgreSQL
+      - name: Test Postgres OrmLite
         working-directory: ServiceStack.OrmLite/tests
         env:
           ORMLITE_DIALECT: PostgreSql11
           PGSQL_CONNECTION: Server=localhost;Port=48303;User Id=test;Password=test;Database=test;Pooling=true;MinPoolSize=0;MaxPoolSize=200
-        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.PostgreSQL.Tests/ServiceStack.OrmLite.PostgreSQL.Tests.csproj --logger 'trx;LogFileName=results.trx'
+        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.SqliteTests/ServiceStack.OrmLite.SqliteTests.csproj --logger 'trx;LogFileName=test-results.trx'
 
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: success() || failure()
-        with:
-          name: OrmLite Tests
-          only-summary: 'true'
-          path: ./ServiceStack.OrmLite/tests/ServiceStack.OrmLite.PostgreSQL.Tests/TestResults/results.trx
-          reporter: dotnet-trx
+      - name: Test SQL Server OrmLite
+        working-directory: ServiceStack.OrmLite/tests
+        env:
+          ORMLITE_DIALECT: SqlServer2017
+          MSSQL_CONNECTION: Server=localhost,48501;Database=master;User Id=sa;Password=Test!tesT;MultipleActiveResultSets=True;
+        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.SqliteTests/ServiceStack.OrmLite.SqliteTests.csproj --logger 'trx;LogFileName=test-results.trx'
+
+#      - name: Test PostgreSQL
+#        working-directory: ServiceStack.OrmLite/tests
+#        env:
+#          ORMLITE_DIALECT: PostgreSql11
+#          PGSQL_CONNECTION: Server=localhost;Port=48303;User Id=test;Password=test;Database=test;Pooling=true;MinPoolSize=0;MaxPoolSize=200
+#        run: dotnet test --framework net6.0 ./ServiceStack.OrmLite.PostgreSQL.Tests/ServiceStack.OrmLite.PostgreSQL.Tests.csproj --logger 'trx;LogFileName=results.trx'
+#
+#      - name: Test Report
+#        uses: dorny/test-reporter@v1
+#        if: success() || failure()
+#        with:
+#          name: OrmLite Tests
+#          only-summary: 'true'
+#          path: ./ServiceStack.OrmLite/tests/ServiceStack.OrmLite.PostgreSQL.Tests/TestResults/results.trx
+#          reporter: dotnet-trx
